version: '3.3'
services:
  proxy_server:
    image: nginx:latest
    container_name: proxy_server
    ports:
      - 80:8080
    depends_on:
      - miniserver
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  miniserver:
    image: mydocker:my
    container_name: miniserver
