version: '3'
services:
  my_little_proxy:
    image: nginx:latest
    container_name: little_server
    ports:
      - 80:8080
    depends_on:
      - my_little_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  my_little_server:
    image: obraz:96.00
    container_name: my_little_server
